version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = ["Dockerfile"]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "browser",
    "nodejs"
  ]

[[transformers]]
name = "prettier"